import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { PDFDownloadLink, Document, Page, Text, View, Image, StyleSheet } from '@react-pdf/renderer'
import { supabase } from '../supabaseClient'

const pdf = StyleSheet.create({ page: { padding: 36, fontFamily: 'Helvetica', fontSize: 12 }, card: { border: '2px solid #1d4ed8', padding: 22, width: 300, margin: 'auto', alignItems: 'center' }, title: { fontSize: 20, textAlign: 'center', marginBottom: 16, color: '#1d4ed8' }, name: { fontSize: 18, textAlign: 'center', marginVertical: 14 }, photo: { width: 88, height: 88, objectFit: 'cover', marginBottom: 10 }, certificateTitle: { fontSize: 25, textAlign: 'center', marginVertical: 28 }, body: { textAlign: 'center', lineHeight: 1.6 } })
function IdCard({ student, schoolName, photoUrl }) { return <Document><Page size="A4" style={pdf.page}><View style={pdf.card}><Text style={pdf.title}>{schoolName || 'School'}{`\n`}STUDENT ID CARD</Text>{photoUrl && <Image src={photoUrl} style={pdf.photo} />}<Text style={pdf.name}>{student.full_name}</Text><Text>Student code: {student.student_code}</Text><Text>Gender: {student.gender || '-'}</Text><Text>Parent: {student.parent_name || '-'}</Text><Text>Phone: {student.parent_phone || '-'}</Text></View></Page></Document> }
function Certificate({ student, certificate, schoolName }) { return <Document><Page size="A4" style={pdf.page}><Text style={pdf.title}>{schoolName || 'School'}</Text><Text style={pdf.certificateTitle}>{certificate.title}</Text><Text style={pdf.body}>This certificate is presented to{`\n\n`}</Text><Text style={pdf.name}>{student.full_name}</Text><Text style={pdf.body}>{certificate.body_text || `For ${certificate.certificate_type}.`}{`\n\n`}Issued: {certificate.issue_date}</Text></Page></Document> }

export default function Documents() {
  const [schoolId, setSchoolId] = useState(''); const [schoolName, setSchoolName] = useState(''); const [students, setStudents] = useState([]); const [certificates, setCertificates] = useState([]); const [studentId, setStudentId] = useState(''); const [photoUrl, setPhotoUrl] = useState(''); const [form, setForm] = useState({ certificate_type: 'Achievement', title: 'Certificate of Achievement', body_text: '', issue_date: new Date().toISOString().slice(0, 10) }); const [message, setMessage] = useState('')
  const selected = students.find((item) => item.id === studentId)
  useEffect(() => { load() }, [])
  useEffect(() => { async function loadPhoto() { if (!selected?.photo_url) return setPhotoUrl(''); const { data } = await supabase.storage.from('student-photos').createSignedUrl(selected.photo_url, 3600); setPhotoUrl(data?.signedUrl || '') } loadPhoto() }, [studentId])
  async function load() { const { data: profile } = await supabase.from('profiles').select('school_id').single(); if (!profile) return; setSchoolId(profile.school_id); const [school, studentData, certificateData] = await Promise.all([supabase.from('schools').select('name').eq('id', profile.school_id).single(), supabase.from('students').select('*').order('full_name'), supabase.from('certificates').select('*, students(full_name)').order('issue_date', { ascending: false })]); setSchoolName(school.data?.name || 'School'); setStudents(studentData.data || []); setCertificates(certificateData.data || []) }
  async function issue(e) { e.preventDefault(); if (!studentId) return setMessage('Choose a student first.'); const { error } = await supabase.from('certificates').insert({ ...form, school_id: schoolId, student_id: studentId }); setMessage(error ? `Error: ${error.message}` : 'Certificate saved.'); if (!error) load() }
  async function remove(id) { if (!window.confirm('Delete this certificate record?')) return; const { error } = await supabase.from('certificates').delete().eq('id', id); setMessage(error ? `Error: ${error.message}` : 'Certificate deleted.'); if (!error) load() }
  const input = { padding: 7, margin: '4px 6px 4px 0' }
  return <div style={{ maxWidth: 850, margin: '40px auto', fontFamily: 'sans-serif' }}><p><Link to="/dashboard">← Dashboard</Link></p><h2>ID Cards & Certificates</h2>{message && <p style={{ color: message.startsWith('Error:') ? 'crimson' : 'green' }}>{message}</p>}<select value={studentId} onChange={(e) => setStudentId(e.target.value)} style={input}><option value="">Choose a student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.full_name} ({student.student_code})</option>)}</select>{selected && <PDFDownloadLink document={<IdCard student={selected} schoolName={schoolName} photoUrl={photoUrl} />} fileName={`${selected.full_name}-id-card.pdf`}>{({ loading }) => <button>{loading ? 'Preparing ID card...' : 'Download ID Card PDF'}</button>}</PDFDownloadLink>}<section style={{ borderTop: '1px solid #ddd', marginTop: 28, paddingTop: 16 }}><h3>Issue Certificate</h3><form onSubmit={issue}><input placeholder="Certificate type" value={form.certificate_type} onChange={(e) => setForm({ ...form, certificate_type: e.target.value })} style={input} /><input required placeholder="Certificate title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} style={input} /><input type="date" value={form.issue_date} onChange={(e) => setForm({ ...form, issue_date: e.target.value })} style={input} /><br /><textarea placeholder="Optional message" value={form.body_text} onChange={(e) => setForm({ ...form, body_text: e.target.value })} style={{ width: 420, height: 70, ...input }} /><br /><button>Save Certificate</button></form></section><section style={{ borderTop: '1px solid #ddd', marginTop: 28, paddingTop: 16 }}><h3>Saved Certificates</h3>{certificates.map((certificate) => { const student = students.find((item) => item.id === certificate.student_id); return <p key={certificate.id}>{certificate.title} - {certificate.students?.full_name} <>{student && <PDFDownloadLink document={<Certificate student={student} certificate={certificate} schoolName={schoolName} />} fileName={`${student.full_name}-certificate.pdf`}>{({ loading }) => <button>{loading ? 'Preparing...' : 'Download PDF'}</button>}</PDFDownloadLink>}</> <button onClick={() => remove(certificate.id)}>Delete</button></p> })}</section></div>
}
